// ResultCode.h

#ifndef __RESULT_CODE_H__
#define __RESULT_CODE_H__

enum ResultCode {
    //Ok code
    RESULT_CODE_OK = 0,
    //Error codes
    RESULT_CODE_ERR_UNSPECIFIED,
    RESULT_CODE_ERR_ARGS,
    RESULT_CODE_ERR_WAV_FILE_SUFFIX,
    RESULT_CODE_ERR_FLAC_FILE_SUFFIX,
    RESULT_CODE_ERR_FILE_OPEN,
    RESULT_CODE_ERR_NO_RIFF_CHUNK_HEADER,
    RESULT_CODE_ERR_READ_RIFF_CHUNK_HEADER,
    RESULT_CODE_ERR_READ_RIFF_CHUNK_SIZE,
    RESULT_CODE_ERR_READ_RIFF_CHUNK_WAVE,
    RESULT_CODE_ERR_NO_RIFF_CHUNK_WAVE,
    RESULT_CODE_ERR_READ_POST_RIFF_CHUNK_HEADER,
    RESULT_CODE_ERR_READ_JUNK_CHUNK_SIZE,
    RESULT_CODE_ERR_READ_JUNK_CHUNK_DATA,
    RESULT_CODE_ERR_READ_FMT_CHUNK_HEADER,
    RESULT_CODE_ERR_NO_FMT_CHUNK_HEADER,
    RESULT_CODE_ERR_READ_FMT_CHUNK_SIZE,
    RESULT_CODE_ERR_READ_FMT_CHUNK_TAG,
    RESULT_CODE_ERR_READ_FMT_CHUNK_NUM_CHANNELS,
    RESULT_CODE_ERR_READ_FMT_CHUNK_SAMPLE_RATE,
    RESULT_CODE_ERR_READ_FMT_CHUNK_AVG_BYTES_PER_SEC,
    RESULT_CODE_ERR_READ_FMT_CHUNK_BLOCK_ALIGN,
    RESULT_CODE_ERR_READ_FMT_CHUNK_BITS_PER_SAMPLE,
    RESULT_CODE_ERR_READ_POST_FMT_CHUNK_HEADER,
    RESULT_CODE_ERR_READ_FLLR_CHUNK_SIZE,
    RESULT_CODE_ERR_READ_FLLR_CHUNK_DATA,
    RESULT_CODE_ERR_READ_BYTES_BEFORE_SAMPLE_DATA,
    RESULT_CODE_ERR_READ_DATA_CHUNK_HEADER,
    RESULT_CODE_ERR_NO_DATA_CHUNK_HEADER,
    RESULT_CODE_ERR_READ_DATA_CHUNK_SIZE,
    RESULT_CODE_ERR_READ_SAMPLE_DATA_BUFFER,
    RESULT_CODE_ERR_ENCODER_ALLOC,
    RESULT_CODE_ERR_ENCODER_SET_VERIFY,
    RESULT_CODE_ERR_ENCODER_SET_COMPRESSION_LEVEL,
    RESULT_CODE_ERR_ENCODER_SET_CHANNELS,
    RESULT_CODE_ERR_ENCODER_SET_BITS_PER_SAMPLE,
    RESULT_CODE_ERR_ENCODER_SET_SAMPLE_RATE,
    RESULT_CODE_ERR_ENCODER_SET_TOTAL_SAMPLES_ESTIMATE,
    RESULT_CODE_ERR_ENCODER_PROCESS_INTERLEAVED,
    RESULT_CODE_ERR_ENCODER_FINISH,
    RESULT_CODE_ERR_OUT_OF_MEMORY_OR_TAG_ERROR,
    RESULT_CODE_ERR_ENCODER_SET_METADATA,
    RESULT_CODE_ERR_ENCODER_INIT,
    RESULT_CODE_ERR_INVALID_NUM_CHANNELS,
    RESULT_CODE_ERR_INVALID_NUM_BITS_PER_SAMPLE,
};

#endif  // __RESULT_CODE_H__
